Repository ROCm/rocSOLVER, pull requests merged in 2021-10, with the labels that each got.

#302 Replace pre-commit hook with post-commit
  .githooks/install
  .githooks/pre-commit
  README.md
  scripts/get-clang-format
  scripts/install-hooks
  scripts/post-commit
  scripts/reformat-files
  scripts/uninstall-hooks
Labels: noCI

#318 Fix docs parameter formatting
  .readthedocs.yaml
  docs/run_doc.sh
  docs/source/requirements.txt
Labels: noOptimizations

#316 Added lasyf
  CHANGELOG.md
  clients/common/lapack_host_reference.cpp
  clients/gtest/CMakeLists.txt
  clients/gtest/lasyf_gtest.cpp
  clients/include/lapack_host_reference.hpp
  clients/include/rocsolver.hpp
  clients/include/rocsolver_dispatcher.hpp
  clients/include/testing_lasyf.hpp
  docs/source/api_auxiliaryfunc.rst
  docs/source/userguide_intro.rst
  library/include/rocsolver-functions.h
  library/src/CMakeLists.txt
  library/src/auxiliary/rocauxiliary_lasyf.cpp
  library/src/auxiliary/rocauxiliary_lasyf.hpp
  library/src/include/lapack_device_functions.hpp
Labels: noOptimizations

#338 Update external-gtest.cmake by bumping googletest to release-1.11.0
  deps/external-gtest.cmake
Labels: noCI, noOptimizations
