Repository ROCm/rocSOLVER, pull requests merged in 2021-06, with the labels that each got.

#259 Use standard library timer functions
  clients/rocblascommon/utility.cpp
  common/src/common_host_helpers.cpp
  library/src/common/rocsolver_logger.cpp
Labels: noOptimizations

#263 Minor code coverage build modifications
  CMakeLists.txt
  install.sh
Labels: noOptimizations

#264 Delete unused rocblascommon code
  clients/rocblascommon/d_vector.hpp
  clients/rocblascommon/host_pinned_vector.hpp
  clients/rocblascommon/pinned_memory_allocator.hpp
  clients/rocblascommon/rocblas_math.hpp
  clients/rocblascommon/rocblas_test.hpp
  clients/rocblascommon/rocblas_vector.hpp
  clients/rocblascommon/utility.cpp
  clients/rocblascommon/utility.hpp
Labels: noOptimizations

#258 Add address sanitizer build option
  CMakeLists.txt
  cmake/armor-config.cmake
  install.sh
Labels: noOptimizations

#260 Use -h to print install.sh help message
  CHANGELOG.md
  install.sh
Labels: noCI, noOptimizations

#266 Update client docs
  docs/source/userguide_clients.rst
  docs/source/userguide_install.rst
  docs/source/userguide_logging.rst
Labels: noOptimizations

#269 Documentation revision 2/3
  docs/source/api_auxiliaryfunc.rst
  docs/source/api_lapackfunc.rst
  docs/source/api_lapacklike.rst
  docs/source/api_types.rst
  docs/source/conf.py
  library/include/rocsolver-extra-types.h
  library/include/rocsolver-functions.h
Labels: noOptimizations

#268 Add profile option to rocsolver-bench
  CHANGELOG.md
  clients/benchmarks/client.cpp
  clients/include/rocsolver_arguments.hpp
  clients/include/testing_bdsqr.hpp
  clients/include/testing_gebd2_gebrd.hpp
  clients/include/testing_gelq2_gelqf.hpp
  clients/include/testing_gels.hpp
  clients/include/testing_geql2_geqlf.hpp
  clients/include/testing_geqr2_geqrf.hpp
  clients/include/testing_gesvd.hpp
  clients/include/testing_getf2_getrf.hpp
  clients/include/testing_getf2_getrf_npvt.hpp
  clients/include/testing_getri.hpp
  clients/include/testing_getri_outofplace.hpp
  clients/include/testing_getrs.hpp
  clients/include/testing_labrd.hpp
  clients/include/testing_lacgv.hpp
  clients/include/testing_larf.hpp
  clients/include/testing_larfb.hpp
  clients/include/testing_larfg.hpp
  clients/include/testing_larft.hpp
  clients/include/testing_laswp.hpp
  clients/include/testing_latrd.hpp
  clients/include/testing_managed_malloc.hpp
  clients/include/testing_orgbr_ungbr.hpp
  clients/include/testing_orglx_unglx.hpp
  clients/include/testing_orgtr_ungtr.hpp
  clients/include/testing_orgxl_ungxl.hpp
  clients/include/testing_orgxr_ungxr.hpp
  clients/include/testing_ormbr_unmbr.hpp
  clients/include/testing_ormlx_unmlx.hpp
  clients/include/testing_ormtr_unmtr.hpp
  clients/include/testing_ormxl_unmxl.hpp
  clients/include/testing_ormxr_unmxr.hpp
  clients/include/testing_potf2_potrf.hpp
  clients/include/testing_stedc.hpp
  clients/include/testing_steqr.hpp
  clients/include/testing_sterf.hpp
  clients/include/testing_syev_heev.hpp
  clients/include/testing_syevd_heevd.hpp
  clients/include/testing_sygsx_hegsx.hpp
  clients/include/testing_sygv_hegv.hpp
  clients/include/testing_sygvd_hegvd.hpp
  clients/include/testing_sytxx_hetxx.hpp
  clients/include/testing_trtri.hpp
Labels: noOptimizations

#272 Minor build fixes
  CMakeLists.txt
  common/CMakeLists.txt
Labels: noOptimizations

#271 bump version and prepare changelog for new development cycle
  CHANGELOG.md
  CMakeLists.txt
  bump_rocsolver_version.sh
  docs/source/conf.py
  library/CMakeLists.txt
Labels: noCI

#273 Reformat CMake code
  CMakeLists.txt
  clients/CMakeLists.txt
  clients/benchmarks/CMakeLists.txt
  clients/gtest/CMakeLists.txt
  clients/samples/CMakeLists.txt
  cmake/armor-config.cmake
  cmake/get-rocm-cmake.cmake
  cmake/os-detection.cmake
  cmake/package-functions.cmake
  cmake/util.cmake
  common/CMakeLists.txt
  library/CMakeLists.txt
  library/src/CMakeLists.txt
Labels: noOptimizations

#280 Change to rocblas trsv template
  library/src/include/rocblas.hpp
  library/src/lapack/roclapack_sygs2_hegs2.cpp
  library/src/lapack/roclapack_sygs2_hegs2.hpp
  library/src/lapack/roclapack_sygs2_hegs2_batched.cpp
  library/src/lapack/roclapack_sygs2_hegs2_strided_batched.cpp
  library/src/lapack/roclapack_sygst_hegst.cpp
  library/src/lapack/roclapack_sygst_hegst.hpp
  library/src/lapack/roclapack_sygst_hegst_batched.cpp
  library/src/lapack/roclapack_sygst_hegst_strided_batched.cpp
Labels: noOptimizations

#278 Build option cleanup
  CHANGELOG.md
  CMakeLists.txt
  install.sh
  library/src/CMakeLists.txt
Labels: noOptimizations

#281 Change hemv template to match rocBLAS
  library/src/auxiliary/rocauxiliary_latrd.hpp
  library/src/include/rocblas.hpp
  library/src/lapack/roclapack_sytd2_hetd2.hpp
Labels: noOptimizations

#276 Upgrade to C++17
  CMakeLists.txt
  common/CMakeLists.txt
  install.sh
Labels: noOptimizations
