Repository ROCm/rocSOLVER, pull requests merged in 2022-12, with the labels that each got.

#460 Improved syevj performance
  CHANGELOG.md
  clients/gtest/syevj_heevj_gtest.cpp
  clients/include/testing_syevj_heevj.hpp
  clients/include/testing_sygvj_hegvj.hpp
  docs/source/design_tuning.rst
  library/include/rocsolver/rocsolver-functions.h
  library/src/include/ideal_sizes.hpp
  library/src/lapack/roclapack_syevj_heevj.cpp
  library/src/lapack/roclapack_syevj_heevj.hpp
  library/src/lapack/roclapack_syevj_heevj_batched.cpp
  library/src/lapack/roclapack_syevj_heevj_strided_batched.cpp
  library/src/lapack/roclapack_sygvj_hegvj.cpp
  library/src/lapack/roclapack_sygvj_hegvj.hpp
  library/src/lapack/roclapack_sygvj_hegvj_batched.cpp
  library/src/lapack/roclapack_sygvj_hegvj_strided_batched.cpp
Labels: noOptimizations

#486 Add gfx1101 to default compilation targets
  CMakeLists.txt
Labels: noOptimizations, noExtendedCI

#485 Added gesvdj
  CHANGELOG.md
  clients/CMakeLists.txt
  clients/common/lapack_host_reference.cpp
  clients/common/testing_gesvdj.cpp
  clients/gtest/CMakeLists.txt
  clients/gtest/gesvdj_gtest.cpp
  clients/include/lapack_host_reference.hpp
  clients/include/rocsolver.hpp
  clients/include/rocsolver_dispatcher.hpp
  clients/include/testing_gesvd.hpp
  clients/include/testing_gesvdj.hpp
  clients/include/testing_gesvdj_notransv.hpp
  clients/include/testing_gesvdx.hpp
  docs/source/api_lapacklike.rst
  docs/source/userguide_intro.rst
  library/include/rocsolver/rocsolver-functions.h
  library/src/CMakeLists.txt
  library/src/include/lib_device_helpers.hpp
  library/src/lapack/roclapack_gesvdj.cpp
  library/src/lapack/roclapack_gesvdj.hpp
  library/src/lapack/roclapack_gesvdj_batched.cpp
  library/src/lapack/roclapack_gesvdj_notransv.cpp
  library/src/lapack/roclapack_gesvdj_notransv.hpp
  library/src/lapack/roclapack_gesvdj_notransv_strided_batched.cpp
  library/src/lapack/roclapack_gesvdj_strided_batched.cpp
  library/src/lapack/roclapack_gesvdx.hpp
Labels: noOptimizations

#492 Add asynchronous execution example
  clients/samples/CMakeLists.txt
  clients/samples/example_graph.c
Labels: noOptimizations, noExtendedCI

#494 Fix getf2_npvt/getrf_npvt singular value tests
  clients/include/testing_getf2_getrf_npvt.hpp
Labels: noOptimizations

#490 Implement lauum
  clients/CMakeLists.txt
  clients/common/lapack_host_reference.cpp
  clients/common/testing_lauum.cpp
  clients/gtest/CMakeLists.txt
  clients/gtest/lauum_gtest.cpp
  clients/include/lapack_host_reference.hpp
  clients/include/rocsolver.hpp
  clients/include/rocsolver_dispatcher.hpp
  clients/include/testing_lauum.hpp
  docs/source/api_auxiliaryfunc.rst
  docs/source/userguide_intro.rst
  library/include/rocsolver/rocsolver-functions.h
  library/src/CMakeLists.txt
  library/src/auxiliary/rocauxiliary_lauum.cpp
  library/src/auxiliary/rocauxiliary_lauum.hpp
Labels: noOptimizations

#489 Completes implementation of divide & conquer method in STEDC
  CHANGELOG.md
  clients/gtest/stedc_gtest.cpp
  clients/gtest/syevd_heevd_gtest.cpp
  clients/gtest/sygvd_hegvd_gtest.cpp
  clients/include/testing_stedc.hpp
  docs/source/design_tuning.rst
  library/src/auxiliary/rocauxiliary_stedc.cpp
  library/src/auxiliary/rocauxiliary_stedc.hpp
  library/src/auxiliary/rocauxiliary_steqr.hpp
  library/src/include/ideal_sizes.hpp
  library/src/include/lib_device_helpers.hpp
  library/src/lapack/roclapack_syevd_heevd.cpp
  library/src/lapack/roclapack_syevd_heevd.hpp
  library/src/lapack/roclapack_syevd_heevd_batched.cpp
  library/src/lapack/roclapack_syevd_heevd_strided_batched.cpp
  library/src/lapack/roclapack_sygvd_hegvd.cpp
  library/src/lapack/roclapack_sygvd_hegvd.hpp
  library/src/lapack/roclapack_sygvd_hegvd_batched.cpp
  library/src/lapack/roclapack_sygvd_hegvd_strided_batched.cpp
Labels: noOptimizations

#495 Update CHANGELOG.md
  CHANGELOG.md
Labels: noCI

#496 Added geblttrf_npvt and geblttrs_npvt
  CHANGELOG.md
  clients/CMakeLists.txt
  clients/benchmarks/client.cpp
  clients/common/testing_geblttrf_npvt.cpp
  clients/common/testing_geblttrs_npvt.cpp
  clients/gtest/CMakeLists.txt
  clients/gtest/geblttrf_gtest.cpp
  clients/gtest/geblttrs_gtest.cpp
  clients/include/rocsolver.hpp
  clients/include/rocsolver_dispatcher.hpp
  clients/include/testing_geblttrf_npvt.hpp
  clients/include/testing_geblttrs_npvt.hpp
  docs/source/api_lapacklike.rst
  docs/source/userguide_intro.rst
  library/include/rocsolver/rocsolver-functions.h
  library/src/CMakeLists.txt
  library/src/lapack/roclapack_geblttrf_npvt.cpp
  library/src/lapack/roclapack_geblttrf_npvt.hpp
  library/src/lapack/roclapack_geblttrf_npvt_batched.cpp
  library/src/lapack/roclapack_geblttrf_npvt_strided_batched.cpp
  library/src/lapack/roclapack_geblttrs_npvt.cpp
  library/src/lapack/roclapack_geblttrs_npvt.hpp
  library/src/lapack/roclapack_geblttrs_npvt_batched.cpp
  library/src/lapack/roclapack_geblttrs_npvt_strided_batched.cpp
Labels: noOptimizations

#497 Disabled failing tests for FC
  CHANGELOG.md
  clients/gtest/managed_malloc_gtest.cpp
  clients/gtest/stedc_gtest.cpp
  clients/gtest/syevd_heevd_gtest.cpp
  clients/gtest/sygvd_hegvd_gtest.cpp
Labels: noOptimizations

#498 Bump versions and prepare changelog for new dev cycle
  CHANGELOG.md
  CMakeLists.txt
  bump_rocsolver_version.sh
  docs/source/conf.py
Labels: noCI

#499 Drop MANAGED_MALLOC HMM tests from test status
  .jenkins/common.groovy
Labels: noOptimizations, noExtendedCI

#501 Modified rocBLAS_iamax
  library/src/include/rocblas.hpp
Labels: noOptimizations

#505 5.5 hotfixes
  CHANGELOG.md
  CMakeLists.txt
  clients/gtest/stedc_gtest.cpp
  clients/gtest/syevd_heevd_gtest.cpp
  clients/gtest/sygvd_hegvd_gtest.cpp
  library/src/auxiliary/rocauxiliary_stedc.hpp
  library/src/lapack/roclapack_syevj_heevj.hpp
Labels: noOptimizations

#506 merging back Release/rocm rel 5.5 hotfixes
  CHANGELOG.md
  CMakeLists.txt
  clients/gtest/stedc_gtest.cpp
  clients/gtest/syevd_heevd_gtest.cpp
  clients/gtest/sygvd_hegvd_gtest.cpp
  library/src/auxiliary/rocauxiliary_stedc.hpp
  library/src/lapack/roclapack_syevj_heevj.hpp
Labels: noOptimizations
