Repository ROCm/rocSOLVER, pull requests merged in 2022-06, with the labels that each got.

#433 GNUInstall Dir enhancements
  CMakeLists.txt
  library/CMakeLists.txt
  library/src/CMakeLists.txt
Labels: noOptimizations, noExtendedCI

#441 fix sygst test code
  clients/include/testing_sygsx_hegsx.hpp
Labels: noOptimizations

#439 Using rocblas header file for block sizes
  library/src/include/rocblas.hpp
Labels: noOptimizations

#442 Updating herk syrk rocblas block sizes
  library/src/include/rocblas.hpp
Labels: noOptimizations

#430 Added sygvdx_inplace
  clients/gtest/CMakeLists.txt
  clients/gtest/sygvdx_hegvdx_gtest.cpp
  clients/include/rocsolver.hpp
  clients/include/testing_sygvdx_hegvdx_inplace.hpp
  library/src/CMakeLists.txt
  library/src/lapack/roclapack_gebrd.hpp
  library/src/lapack/roclapack_sygst_hegst.hpp
  library/src/lapack/roclapack_sygv_hegv.hpp
  library/src/lapack/roclapack_sygvd_hegvd.hpp
  library/src/lapack/roclapack_sygvdx_hegvdx_inplace.cpp
  library/src/lapack/roclapack_sygvdx_hegvdx_inplace.hpp
  library/src/lapack/roclapack_sygvx_hegvx.hpp
  library/src/lapack/roclapack_sytrd_hetrd.hpp
Labels: noOptimizations

#427 Added syevj
  CHANGELOG.md
  clients/benchmarks/client.cpp
  clients/gtest/CMakeLists.txt
  clients/gtest/syevj_heevj_gtest.cpp
  clients/include/rocsolver.hpp
  clients/include/rocsolver_dispatcher.hpp
  clients/include/testing_syevj_heevj.hpp
  docs/source/api_lapacklike.rst
  docs/source/userguide_intro.rst
  library/include/rocsolver/rocsolver-functions.h
  library/src/CMakeLists.txt
  library/src/lapack/roclapack_syevj_heevj.cpp
  library/src/lapack/roclapack_syevj_heevj.hpp
  library/src/lapack/roclapack_syevj_heevj_batched.cpp
  library/src/lapack/roclapack_syevj_heevj_strided_batched.cpp
  library/src/lapack/roclapack_sygvdx_hegvdx_inplace.hpp
Labels: noOptimizations

#446 Added sygvj
  CHANGELOG.md
  clients/gtest/CMakeLists.txt
  clients/gtest/sygvj_hegvj_gtest.cpp
  clients/include/rocsolver.hpp
  clients/include/rocsolver_dispatcher.hpp
  clients/include/testing_sygvj_hegvj.hpp
  docs/source/api_lapacklike.rst
  docs/source/userguide_intro.rst
  library/include/rocsolver/rocsolver-functions.h
  library/src/CMakeLists.txt
  library/src/lapack/roclapack_sygvj_hegvj.cpp
  library/src/lapack/roclapack_sygvj_hegvj.hpp
  library/src/lapack/roclapack_sygvj_hegvj_batched.cpp
  library/src/lapack/roclapack_sygvj_hegvj_strided_batched.cpp
Labels: noOptimizations

#438 Fix git safe.directory error on dependency install
  CHANGELOG.md
  deps/CMakeLists.txt
  deps/cmake/get-cli-arguments.cmake
  deps/external-gtest.cmake
  deps/external-lapack.cmake
  install.sh
Labels: noOptimizations, noExtendedCI

#448 syevj Nonsorting option
  clients/benchmarks/client.cpp
  clients/gtest/syevj_heevj_gtest.cpp
  clients/include/rocsolver.hpp
  clients/include/rocsolver_arguments.hpp
  clients/include/testing_syevj_heevj.hpp
  common/include/rocsolver_datatype2string.hpp
  docs/source/api_types.rst
  library/include/rocsolver/rocsolver-extra-types.h
  library/include/rocsolver/rocsolver-functions.h
  library/src/include/rocsolver_logvalue.hpp
  library/src/lapack/roclapack_syevj_heevj.cpp
  library/src/lapack/roclapack_syevj_heevj.hpp
  library/src/lapack/roclapack_syevj_heevj_batched.cpp
  library/src/lapack/roclapack_syevj_heevj_strided_batched.cpp
  library/src/lapack/roclapack_sygvj_hegvj.hpp
Labels: noOptimizations

#444 Add GitHub actions file for docs build
  .github/workflows/docs.yaml
Labels: noCI

#451 Bump version and prepare changelog for new dev cycle
  .github/CODEOWNERS
  CHANGELOG.md
  CMakeLists.txt
  bump_rocsolver_version.sh
  docs/source/conf.py
Labels: noCI
