Repository ROCm/rocSOLVER, pull requests merged in 2022-09, with the labels that each got.

#468 Added bdsvdx
  CHANGELOG.md
  clients/CMakeLists.txt
  clients/benchmarks/client.cpp
  clients/common/lapack_host_reference.cpp
  clients/common/testing_bdsvdx.cpp
  clients/gtest/CMakeLists.txt
  clients/gtest/bdsvdx_gtest.cpp
  clients/include/lapack_host_reference.hpp
  clients/include/rocsolver.hpp
  clients/include/rocsolver_arguments.hpp
  clients/include/rocsolver_dispatcher.hpp
  clients/include/testing_bdsvdx.hpp
  common/include/rocsolver_datatype2string.hpp
  docs/source/api_auxiliaryfunc.rst
  docs/source/api_types.rst
  docs/source/userguide_intro.rst
  library/include/rocsolver/rocsolver-extra-types.h
  library/include/rocsolver/rocsolver-functions.h
  library/src/CMakeLists.txt
  library/src/auxiliary/rocauxiliary_bdsvdx.cpp
  library/src/auxiliary/rocauxiliary_bdsvdx.hpp
  library/src/include/rocsolver_logvalue.hpp
Labels: noOptimizations

#469 Update Ubuntu version for static analysis job
  .jenkins/staticanalysis.groovy
Labels: noOptimizations, noExtendedCI

#470 Add partial SVD routine gesvdx
  CHANGELOG.md
  clients/CMakeLists.txt
  clients/common/lapack_host_reference.cpp
  clients/common/testing_gesvdx.cpp
  clients/gtest/CMakeLists.txt
  clients/gtest/gesvdx_gtest.cpp
  clients/include/lapack_host_reference.hpp
  clients/include/rocsolver.hpp
  clients/include/rocsolver_dispatcher.hpp
  clients/include/testing_bdsvdx.hpp
  clients/include/testing_gesvdx.hpp
  docs/source/api_lapackfunc.rst
  docs/source/userguide_intro.rst
  library/include/rocsolver/rocsolver-functions.h
  library/src/CMakeLists.txt
  library/src/auxiliary/rocauxiliary_bdsvdx.hpp
  library/src/auxiliary/rocauxiliary_ormlq_unmlq.hpp
  library/src/auxiliary/rocauxiliary_ormqr_unmqr.hpp
  library/src/include/lib_device_helpers.hpp
  library/src/lapack/roclapack_gesvd.hpp
  library/src/lapack/roclapack_gesvdx.cpp
  library/src/lapack/roclapack_gesvdx.hpp
  library/src/lapack/roclapack_gesvdx_batched.cpp
  library/src/lapack/roclapack_gesvdx_strided_batched.cpp
Labels: noOptimizations

#472 Bump version and prepare changelog for new dev cycle
  CHANGELOG.md
  CMakeLists.txt
  bump_rocsolver_version.sh
  docs/source/conf.py
Labels: noCI
