Repository ROCm/rocSOLVER, pull requests merged in 2023-10, with the labels that each got.

#615 Fix debug build for CSRRF tests
  clients/include/testing_csrrf_analysis.hpp
  clients/include/testing_csrrf_workflow.hpp
  common/include/common_host_helpers.hpp
Labels: noOptimizations

#618 bump versions
  CMakeLists.txt
  bump_rocsolver_version.sh
Labels: noOptimizations, noExtendedCI

#626 Documentation standardization
  .github/dependabot.yml
  .readthedocs.yaml
  README.md
  docs/.gitignore
  docs/conf.py
  docs/doxygen/Doxyfile
  docs/license.md
  docs/sphinx/_toc.yml.in
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: dependencies, ci:docs-only
