Repository ROCm/rocSOLVER, pull requests merged in 2023-08, with the labels that each got.

#583 Fix stack overflow in sparse tests on Windows
  clients/CMakeLists.txt
  clients/common/rocsolver_test.cpp
  clients/include/rocsolver_test.hpp
  clients/rocblascommon/clients_utility.cpp
Labels: noExtendedCI

#593 Divide & conquer + Jacobi (part 1)
  clients/gtest/syevj_heevj_gtest.cpp
  library/src/auxiliary/rocauxiliary_stedc.hpp
  library/src/lapack/roclapack_syevj_heevj.hpp
Labels: noOptimizations

#594 366827 - Disable file reorg backward compatibility support by default
  CMakeLists.txt
  install.sh
Labels: noOptimizations

#598 Merge back 5.7 release branch fixes
  CHANGELOG.md
Labels: noOptimizations, noExtendedCI, ci:docs-only
