Repository ROCm/rocSOLVER, pull requests merged in 2023-05, with the labels that each got.

#548 Update documentation requirements
  docs/.sphinx/requirements.in
  docs/.sphinx/requirements.txt
Labels: noOptimizations, noExtendedCI

#549 Interleaved batched methods for geblttrf and geblttrs
  CHANGELOG.md
  clients/CMakeLists.txt
  clients/benchmarks/client.cpp
  clients/common/testing_geblttrf_npvt_interleaved.cpp
  clients/common/testing_geblttrs_npvt_interleaved.cpp
  clients/gtest/geblttrf_gtest.cpp
  clients/gtest/geblttrs_gtest.cpp
  clients/gtest/logging_gtest.cpp
  clients/include/rocsolver.hpp
  clients/include/testing_geblttrf_npvt_interleaved.hpp
  clients/include/testing_geblttrs_npvt_interleaved.hpp
  common/include/common_host_helpers.hpp
  docs/api/lapacklike.rst
  library/include/rocsolver/rocsolver-functions.h
  library/src/CMakeLists.txt
  library/src/auxiliary/rocauxiliary_laswp.cpp
  library/src/auxiliary/rocauxiliary_laswp.hpp
  library/src/auxiliary/rocauxiliary_lasyf.hpp
  library/src/include/lapack_device_functions.hpp
  library/src/include/lib_host_helpers.hpp
  library/src/include/rocsolver_run_specialized_kernels.hpp
  library/src/lapack/roclapack_geblttrf_npvt.cpp
  library/src/lapack/roclapack_geblttrf_npvt.hpp
  library/src/lapack/roclapack_geblttrf_npvt_batched.cpp
  library/src/lapack/roclapack_geblttrf_npvt_interleaved_batched.cpp
  library/src/lapack/roclapack_geblttrf_npvt_strided_batched.cpp
  library/src/lapack/roclapack_geblttrs_npvt.cpp
  library/src/lapack/roclapack_geblttrs_npvt.hpp
  library/src/lapack/roclapack_geblttrs_npvt_batched.cpp
  library/src/lapack/roclapack_geblttrs_npvt_interleaved_batched.cpp
  library/src/lapack/roclapack_geblttrs_npvt_strided_batched.cpp
  library/src/lapack/roclapack_gesv.hpp
  library/src/lapack/roclapack_gesv_outofplace.hpp
  library/src/lapack/roclapack_getf2.cpp
  library/src/lapack/roclapack_getf2.hpp
  library/src/lapack/roclapack_getf2_batched.cpp
  library/src/lapack/roclapack_getf2_strided_batched.cpp
  library/src/lapack/roclapack_getrf.cpp
  library/src/lapack/roclapack_getrf.hpp
  library/src/lapack/roclapack_getrf_batched.cpp
  library/src/lapack/roclapack_getrf_strided_batched.cpp
  library/src/lapack/roclapack_getri_outofplace.hpp
  library/src/lapack/roclapack_getrs.cpp
  library/src/lapack/roclapack_getrs.hpp
  library/src/lapack/roclapack_getrs_batched.cpp
  library/src/lapack/roclapack_getrs_strided_batched.cpp
  library/src/specialized/roclapack_gemm_specialized_kernels.hpp
  library/src/specialized/roclapack_gemm_specialized_kernels_c.cpp
  library/src/specialized/roclapack_gemm_specialized_kernels_d.cpp
  library/src/specialized/roclapack_gemm_specialized_kernels_s.cpp
  library/src/specialized/roclapack_gemm_specialized_kernels_z.cpp
  library/src/specialized/roclapack_ger_specialized_kernels.hpp
  library/src/specialized/roclapack_ger_specialized_kernels_c.cpp
  library/src/specialized/roclapack_ger_specialized_kernels_d.cpp
  library/src/specialized/roclapack_ger_specialized_kernels_s.cpp
  library/src/specialized/roclapack_ger_specialized_kernels_z.cpp
  library/src/specialized/roclapack_trsm_specialized_kernels.hpp
Labels: runPerformance

#554 Remove undefined ger instantiations
  library/src/specialized/roclapack_ger_specialized_kernels.hpp
  library/src/specialized/roclapack_ger_specialized_kernels_d.cpp
  library/src/specialized/roclapack_ger_specialized_kernels_s.cpp
Labels: noOptimizations, noExtendedCI

#553 Fix failing Windows build
  clients/include/testing_csrrf_analysis.hpp
  clients/include/testing_csrrf_refactlu.hpp
  clients/include/testing_csrrf_solve.hpp
  clients/include/testing_csrrf_splitlu.hpp
  clients/include/testing_csrrf_sumlu.hpp
Labels: noOptimizations, noExtendedCI

#557 Check for test data relative to running executable
  clients/include/rocsolver_test.hpp
  clients/rocblascommon/clients_utility.cpp
  clients/rocblascommon/clients_utility.hpp
Labels: noOptimizations
