Repository ROCm/rocSOLVER, pull requests merged in 2023-09, with the labels that each got.

#600 Resolve test failures
  clients/gtest/memory_model_gtest.cpp
  clients/include/testing_csrrf_refactchol.hpp
  library/src/specialized/roclapack_trsm_specialized_kernels.hpp
Labels: noOptimizations

#574 Updated rocSOLVER APIs documentation
  docs/api/auxiliary.rst
  docs/api/lapack.rst
  docs/api/lapacklike.rst
  docs/api/refact.rst
  docs/design/batch.rst
  docs/userguide/examples.rst
  docs/userguide/intro.rst
  library/include/rocsolver/rocsolver-functions.h
Labels: noOptimizations, noExtendedCI

#603 Implement test for GETRF with large matrices.
  clients/gtest/CMakeLists.txt
  clients/gtest/getrf_large_gtest.cpp
  clients/include/rocsolver.hpp
  clients/include/testing_getrf_large.hpp
Labels: noOptimizations

#605 CHANGELOG for 6.0 FC
  CHANGELOG.md
Labels: noCI

#606 bump versions and prepare changelog for next dev cycle
  CHANGELOG.md
  CMakeLists.txt
  bump_rocsolver_version.sh
Labels: noCI

#614 Revert "bump versions and prepare changelog for next dev cycle (#606)"
  CMakeLists.txt
  bump_rocsolver_version.sh
Labels: noCI

#613 replace build.image with build.os in the .readthedocs.yaml config
  .readthedocs.yaml
Labels: dependencies, ci:docs-only
