Repository ROCm/rocSOLVER, pull requests merged in 2023-01, with the labels that each got.

#491 Remove host_vector and device_vector from clients
  clients/include/clientcommon.hpp
  clients/include/norm.hpp
  clients/rocblascommon/device_vector.hpp
  clients/rocblascommon/host_vector.hpp
  clients/rocblascommon/rocblas_vector.hpp
Labels: noOptimizations, noExtendedCI

#507 Move internal headers to a subdirectory
  CHANGELOG.md
  docs/Doxyfile
  library/CMakeLists.txt
  library/include/rocsolver/internal/rocsolver-aliases.h
  library/include/rocsolver/internal/rocsolver-extra-types.h
  library/include/rocsolver/internal/rocsolver-functions.h
  library/include/rocsolver/internal/rocsolver-version.h.in
  library/include/rocsolver/rocsolver.h
  library/src/CMakeLists.txt
Labels: noOptimizations, noExtendedCI

#508 Revert "Remove rpath/runpath from ROCm binaries and libraries (#483)"
  install.sh
Labels: noExtendedCI

#512 Hide symbols for GPU kernels
  library/src/include/lib_macros.hpp
Labels: noExtendedCI

#513 Fix reserved identifiers in include guards
  CONTRIBUTING.md
  library/include/rocsolver/internal/rocsolver-extra-types.h
  library/include/rocsolver/internal/rocsolver-functions.h
  library/include/rocsolver/internal/rocsolver-version.h.in
  library/include/rocsolver/rocsolver.h
Labels: noOptimizations, noExtendedCI

#515 Fix use of fmt 9.0 and later in logging test
  clients/gtest/logging_gtest.cpp
Labels: noOptimizations, noExtendedCI

#511 Remove deprecated functions and types
  CHANGELOG.md
  docs/source/api_deprecated.rst
  docs/source/api_index.rst
  library/CMakeLists.txt
  library/include/rocsolver/internal/rocsolver-aliases.h
  library/include/rocsolver/rocsolver.h
  library/src/CMakeLists.txt
  library/src/auxiliary/rocauxiliary_aliases.cpp
Labels: noOptimizations, noExtendedCI

#493 Check HIP API return values on all calls
  clients/gtest/memory_model_gtest.cpp
  clients/include/testing_managed_malloc.hpp
  clients/rocblascommon/d_vector.hpp
  common/CMakeLists.txt
  common/include/common_host_helpers.hpp
  common/src/common_host_helpers.cpp
  library/src/lapack/roclapack_syevdx_heevdx_inplace.hpp
  library/src/lapack/roclapack_syevj_heevj.hpp
  library/src/lapack/roclapack_sygvdx_hegvdx_inplace.hpp
Labels: noOptimizations

#509 workaround for hetrd
  library/src/lapack/roclapack_sytd2_hetd2.hpp
Labels: noOptimizations, noExtendedCI

#520 5.5 hotfixes (2)
  .jenkins/common.groovy
  library/src/auxiliary/rocauxiliary_lauum.hpp
  library/src/auxiliary/rocauxiliary_stedc.hpp
Labels: noOptimizations

#521 merging back rocm rel 5.5 hotfixes (2)
  library/src/auxiliary/rocauxiliary_lauum.hpp
  library/src/auxiliary/rocauxiliary_stedc.hpp
Labels: noOptimizations
