Repository ROCm/rocSOLVER, pull requests merged in 2024-03, with the labels that each got.

#682 Remove unused immintrin.h include
  clients/rocblascommon/rocblas_math.hpp
Labels: noOptimizations, noExtendedCI

#651 Improve performance of sorting eigenvalues and eigenvectors using shell sort
  CHANGELOG.md
  library/src/auxiliary/rocauxiliary_bdsqr.cpp
  library/src/auxiliary/rocauxiliary_bdsqr.hpp
  library/src/auxiliary/rocauxiliary_bdsvdx.cpp
  library/src/auxiliary/rocauxiliary_bdsvdx.hpp
  library/src/auxiliary/rocauxiliary_stedc.cpp
  library/src/auxiliary/rocauxiliary_stedc.hpp
  library/src/auxiliary/rocauxiliary_stedcj.hpp
  library/src/include/lib_device_helpers.hpp
  library/src/lapack/roclapack_syevdx_heevdx_inplace.cpp
  library/src/lapack/roclapack_syevdx_heevdx_inplace.hpp
  library/src/lapack/roclapack_syevx_heevx.cpp
  library/src/lapack/roclapack_syevx_heevx.hpp
  library/src/lapack/roclapack_syevx_heevx_batched.cpp
  library/src/lapack/roclapack_syevx_heevx_strided_batched.cpp
Labels: noOptimizations

#684 Update links
  docs/userguide/clients.rst
  docs/userguide/install.rst
  docs/userguide/memory.rst
Labels: ci:docs-only, documentation

#687 codeowners update
  .github/CODEOWNERS
Labels: noCI

#677 Re-enable static library CI job
  .jenkins/common.groovy
  .jenkins/static.groovy
Labels: ci:static-libraries
