Repository ROCm/rocSOLVER, pull requests merged in 2024-05, with the labels that each got.

#708 Docs: fix links in installation and types guides
  docs/howto/index.rst
  docs/index.rst
  docs/installation/installlinux.rst
  docs/reference/types.rst
  docs/sphinx/_toc.yml.in
Labels: ci:docs-only, documentation

#711 Update soversion
  bump_rocsolver_version.sh
  library/CMakeLists.txt
Labels: noOptimizations, noExtendedCI

#729 Update syevdx_inplace
  clients/common/lapack/testing_syevdx_heevdx_inplace.hpp
  clients/common/lapack/testing_sygvdx_hegvdx_inplace.hpp
  library/src/lapack/roclapack_syevdx_heevdx_inplace.cpp
  library/src/lapack/roclapack_syevdx_heevdx_inplace.hpp
  library/src/lapack/roclapack_sygvdx_hegvdx_inplace.cpp
  library/src/lapack/roclapack_sygvdx_hegvdx_inplace.hpp
Labels: noOptimizations
