Repository ROCm/rocSOLVER, pull requests merged in 2024-01, with the labels that each got.

#643 Divide & Conquer + Jacobi (part 2)
  CHANGELOG.md
  clients/CMakeLists.txt
  clients/common/testing_syevdj_heevdj.cpp
  clients/common/testing_sygvdj_hegvdj.cpp
  clients/gtest/CMakeLists.txt
  clients/gtest/syevdj_heevdj_gtest.cpp
  clients/gtest/sygvdj_hegvdj_gtest.cpp
  clients/include/rocsolver.hpp
  clients/include/rocsolver_dispatcher.hpp
  clients/include/testing_syevdj_heevdj.hpp
  clients/include/testing_sygvdj_hegvdj.hpp
  docs/api/lapacklike.rst
  docs/design/tuning.rst
  docs/userguide/intro.rst
  library/include/rocsolver/rocsolver-functions.h
  library/src/CMakeLists.txt
  library/src/auxiliary/rocauxiliary_stedc.hpp
  library/src/include/ideal_sizes.hpp
  library/src/lapack/roclapack_syevdj_heevdj.cpp
  library/src/lapack/roclapack_syevdj_heevdj.hpp
  library/src/lapack/roclapack_syevdj_heevdj_batched.cpp
  library/src/lapack/roclapack_syevdj_heevdj_strided_batched.cpp
  library/src/lapack/roclapack_syevj_heevj.hpp
  library/src/lapack/roclapack_sygvdj_hegvdj.cpp
  library/src/lapack/roclapack_sygvdj_hegvdj.hpp
  library/src/lapack/roclapack_sygvdj_hegvdj_batched.cpp
  library/src/lapack/roclapack_sygvdj_hegvdj_strided_batched.cpp
Labels: noOptimizations

#647 Update ReadtheDocs links to new documentation sites
  CHANGELOG.md
  CONTRIBUTING.md
  clients/samples/example_basic.c
  clients/samples/example_basic.cpp
  clients/samples/example_graph.c
  clients/samples/example_hmm.c
  clients/samples/example_logging.cpp
  docs/api/deprecated.rst
  docs/api/types.rst
  docs/userguide/clients.rst
  docs/userguide/install.rst
  docs/userguide/logging.rst
  docs/userguide/memory.rst
  install.sh
Labels: ci:docs-only, documentation

#648 merge back Divide & Conquer + Jacobi (part 2) into develop
  CHANGELOG.md
  clients/CMakeLists.txt
  clients/common/testing_syevdj_heevdj.cpp
  clients/common/testing_sygvdj_hegvdj.cpp
  clients/gtest/CMakeLists.txt
  clients/gtest/syevdj_heevdj_gtest.cpp
  clients/gtest/sygvdj_hegvdj_gtest.cpp
  clients/include/rocsolver.hpp
  clients/include/rocsolver_dispatcher.hpp
  clients/include/testing_syevdj_heevdj.hpp
  clients/include/testing_sygvdj_hegvdj.hpp
  docs/api/lapacklike.rst
  docs/design/tuning.rst
  docs/userguide/intro.rst
  library/include/rocsolver/rocsolver-functions.h
  library/src/CMakeLists.txt
  library/src/auxiliary/rocauxiliary_stedc.hpp
  library/src/include/ideal_sizes.hpp
  library/src/lapack/roclapack_syevdj_heevdj.cpp
  library/src/lapack/roclapack_syevdj_heevdj.hpp
  library/src/lapack/roclapack_syevdj_heevdj_batched.cpp
  library/src/lapack/roclapack_syevdj_heevdj_strided_batched.cpp
  library/src/lapack/roclapack_syevj_heevj.hpp
  library/src/lapack/roclapack_sygvdj_hegvdj.cpp
  library/src/lapack/roclapack_sygvdj_hegvdj.hpp
  library/src/lapack/roclapack_sygvdj_hegvdj_batched.cpp
  library/src/lapack/roclapack_sygvdj_hegvdj_strided_batched.cpp
Labels: noOptimizations

#658 Drop gfx803 and gfx900 from default build targets
  CHANGELOG.md
  CMakeLists.txt
Labels: noExtendedCI
