Repository ROCm/rocSOLVER, pull requests merged in 2024-10, with the labels that each got.

#815 Add option to disable rocBLAS in rocsolver_gemm/_trsm
  CMakeLists.txt
  library/src/CMakeLists.txt
  library/src/auxiliary/rocauxiliary_larfb.hpp
  library/src/auxiliary/rocauxiliary_stedc.hpp
  library/src/include/rocsolver_run_specialized_kernels.hpp
  library/src/lapack/roclapack_geblttrf_npvt.hpp
  library/src/lapack/roclapack_geblttrs_npvt.hpp
  library/src/lapack/roclapack_gebrd.hpp
  library/src/lapack/roclapack_gesvd.hpp
  library/src/lapack/roclapack_gesvdj.hpp
  library/src/lapack/roclapack_gesvdj_notransv.hpp
  library/src/lapack/roclapack_getrf.hpp
  library/src/lapack/roclapack_getri.hpp
  library/src/specialized/roclapack_gemm_specialized_kernels.hpp
  library/src/specialized/roclapack_gemm_specialized_kernels_c.cpp
  library/src/specialized/roclapack_gemm_specialized_kernels_d.cpp
  library/src/specialized/roclapack_gemm_specialized_kernels_s.cpp
  library/src/specialized/roclapack_gemm_specialized_kernels_z.cpp
  library/src/specialized/roclapack_trsm_specialized_kernels.hpp
Labels: noOptimizations

#830 Fix libfmt build errors (#828)
  clients/benchmarks/client.cpp
  clients/common/misc/rocblas_test.hpp
Labels: noOptimizations

#829 [Doc] Cherry pick - Bump rocm-docs-core from 1.7.2 to 1.8.2 in /docs/sphinx (#824)
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: ci:docs-only, documentation

#834 Convert change log to new format
  CHANGELOG.md
Labels: ci:docs-only

#833 Convert change log to new format
  CHANGELOG.md
Labels: ci:docs-only

#825 scripts for performance tracking system
  .github/CODEOWNERS
  scripts/perf/README.md
  scripts/perf/perfoptim-suite
  scripts/perf/rocsolver-perfoptim-suite.py
Labels: noOptimizations, runPerformance

#840 Fix static builds
  library/src/CMakeLists.txt
  library/src/refact/rocsolver_rfinfo.cpp
Labels: noOptimizations

#841 merge release-staging/rocm-rel-6.3 back into develop
  CHANGELOG.md
  docs/howto/memory.rst
Labels: noOptimizations, noExtendedCI

#839 Add note to the readme file
  README.md
Labels: ci:docs-only, documentation
