Repository ROCm/rocSOLVER, pull requests merged in 2024-04, with the labels that each got.

#665 optimization of Cholesky factorization
  CHANGELOG.md
  library/src/CMakeLists.txt
  library/src/include/ideal_sizes.hpp
  library/src/include/rocblas.hpp
  library/src/include/rocsolver_run_specialized_kernels.hpp
  library/src/lapack/roclapack_potf2.hpp
  library/src/lapack/roclapack_potrf.hpp
  library/src/specialized/roclapack_potf2_specialized_kernels.hpp
  library/src/specialized/roclapack_potf2_specialized_kernels_c.cpp
  library/src/specialized/roclapack_potf2_specialized_kernels_d.cpp
  library/src/specialized/roclapack_potf2_specialized_kernels_s.cpp
  library/src/specialized/roclapack_potf2_specialized_kernels_z.cpp
  library/src/specialized/roclapack_trsm_specialized_kernels.hpp
Labels: noOptimizations

#696 Cleanup to stedcj
  library/src/auxiliary/rocauxiliary_stedcj.cpp
  library/src/auxiliary/rocauxiliary_stedcj.hpp
Labels: noOptimizations, noExtendedCI

#695 Added getrs_64
  CHANGELOG.md
  clients/common/containers/device_batch_vector.hpp
  clients/common/containers/device_strided_batch_vector.hpp
  clients/common/containers/host_batch_vector.hpp
  clients/common/containers/host_strided_batch_vector.hpp
  clients/common/containers/rocblas_vector.hpp
  clients/common/lapack/testing_getrs.cpp
  clients/common/lapack/testing_getrs.hpp
  clients/common/misc/client_util.hpp
  clients/common/misc/rocsolver.hpp
  clients/common/misc/rocsolver_dispatcher.hpp
  clients/gtest/lapack/getrs_gtest.cpp
  common/include/rocblas_utility.hpp
  docs/reference/lapack.rst
  library/include/rocsolver/rocsolver-functions.h
  library/src/auxiliary/rocauxiliary_laswp.cpp
  library/src/auxiliary/rocauxiliary_laswp.hpp
  library/src/include/lib_device_helpers.hpp
  library/src/include/lib_host_helpers.hpp
  library/src/include/rocblas.hpp
  library/src/include/rocsolver_run_specialized_kernels.hpp
  library/src/lapack/roclapack_geblttrf_npvt.hpp
  library/src/lapack/roclapack_geblttrf_npvt_interleaved_batched.cpp
  library/src/lapack/roclapack_geblttrs_npvt.hpp
  library/src/lapack/roclapack_geblttrs_npvt_interleaved_batched.cpp
  library/src/lapack/roclapack_getrf.cpp
  library/src/lapack/roclapack_getrf.hpp
  library/src/lapack/roclapack_getrf_batched.cpp
  library/src/lapack/roclapack_getrf_strided_batched.cpp
  library/src/lapack/roclapack_getri.hpp
  library/src/lapack/roclapack_getrs.cpp
  library/src/lapack/roclapack_getrs.hpp
  library/src/lapack/roclapack_getrs_batched.cpp
  library/src/lapack/roclapack_getrs_strided_batched.cpp
  library/src/lapack/roclapack_trtri.hpp
  library/src/specialized/roclapack_trsm_specialized_kernels.hpp
  library/src/specialized/roclapack_trsm_specialized_kernels_c.cpp
  library/src/specialized/roclapack_trsm_specialized_kernels_d.cpp
  library/src/specialized/roclapack_trsm_specialized_kernels_s.cpp
  library/src/specialized/roclapack_trsm_specialized_kernels_z.cpp
Labels: noOptimizations

#631 splitLU optimization
  .jenkins/common.groovy
  CHANGELOG.md
  CMakeLists.txt
  library/src/CMakeLists.txt
  library/src/include/ideal_sizes.hpp
  library/src/refact/rocrefact_csrrf_splitlu.cpp
  library/src/refact/rocrefact_csrrf_splitlu.hpp
Labels: noOptimizations

#672 Switch from using hipcc to using Clang compiler
  common/CMakeLists.txt
  docs/installation/installlinux.rst
  install.sh
  library/src/CMakeLists.txt
  toolchain-linux.cmake
Labels: noExtendedCI, runPerformance

#704 bump versions and prepare changelog for new dev cycle
  CHANGELOG.md
  CMakeLists.txt
  bump_rocsolver_version.sh
Labels: noCI

#705 Disable `user_owned` memory test for 6.2 release.
  clients/gtest/memory_model_gtest.cpp
Labels: noOptimizations

#707 Disable `user_owned` memory test for 6.2 release. (#705)
  clients/gtest/memory_model_gtest.cpp
Labels: noOptimizations
