Repository ROCm/rocSOLVER, pull requests merged in 2024-07, with the labels that each got.

#756 Docs pick 6.2
  .readthedocs.yaml
  docs/howto/index.rst
  docs/index.rst
  docs/installation/installlinux.rst
  docs/reference/types.rst
  docs/sphinx/_toc.yml.in
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: ci:docs-only, documentation

#755 Fix memory allocation issues in Jacobi solvers
  library/src/lapack/roclapack_syevj_heevj.cpp
  library/src/lapack/roclapack_syevj_heevj_batched.cpp
  library/src/lapack/roclapack_syevj_heevj_strided_batched.cpp
Labels: noOptimizations

#760 Use std::min and std::max
  clients/common/auxiliary/testing_bdsqr.hpp
  clients/common/auxiliary/testing_labrd.hpp
  clients/common/auxiliary/testing_orgbr_ungbr.hpp
  clients/common/auxiliary/testing_orgtr_ungtr.hpp
  clients/common/auxiliary/testing_ormbr_unmbr.hpp
  clients/common/auxiliary/testing_ormlx_unmlx.hpp
  clients/common/auxiliary/testing_ormxl_unmxl.hpp
  clients/common/auxiliary/testing_ormxr_unmxr.hpp
  clients/common/lapack/testing_gebd2_gebrd.hpp
  clients/common/lapack/testing_geblttrf_npvt_interleaved.hpp
  clients/common/lapack/testing_geblttrs_npvt_interleaved.hpp
  clients/common/lapack/testing_gels.hpp
  clients/common/lapack/testing_gels_outofplace.hpp
  clients/common/lapack/testing_gesvd.hpp
  clients/common/lapack/testing_gesvdj.hpp
  clients/common/lapack/testing_gesvdj_notransv.hpp
  clients/common/lapack/testing_gesvdx.hpp
  clients/common/lapack/testing_gesvdx_notransv.hpp
  clients/gtest/testing_managed_malloc.hpp
  common/include/common_host_helpers.hpp
  library/src/auxiliary/rocauxiliary_stedcj.hpp
  library/src/include/lapack_device_functions.hpp
  library/src/include/lib_device_helpers.hpp
  library/src/lapack/roclapack_syevx_heevx.hpp
  library/src/lapack/roclapack_sygvdx_hegvdx.hpp
  library/src/lapack/roclapack_sygvdx_hegvdx_inplace.hpp
  library/src/refact/rocrefact_csrrf_splitlu.hpp
  library/src/specialized/roclapack_getf2_specialized_kernels.hpp
Labels: noOptimizations, noExtendedCI

#761 Updates to types and index
  docs/index.rst
  docs/installation/installlinux.rst
  docs/reference/types.rst
  docs/sphinx/_toc.yml.in
Labels: ci:docs-only, documentation

#762 Fix jacobi cycle-sync
  library/src/lapack/roclapack_syevj_heevj.hpp
Labels: noOptimizations

#747 Add 64-bit versions of lacgv, larf, and larfg
  CHANGELOG.md
  clients/common/auxiliary/testing_lacgv.cpp
  clients/common/auxiliary/testing_lacgv.hpp
  clients/common/auxiliary/testing_larf.cpp
  clients/common/auxiliary/testing_larf.hpp
  clients/common/auxiliary/testing_larfg.cpp
  clients/common/auxiliary/testing_larfg.hpp
  clients/common/misc/rocsolver.hpp
  clients/common/misc/rocsolver_dispatcher.hpp
  clients/gtest/auxiliary/lacgv_gtest.cpp
  clients/gtest/auxiliary/larf_gtest.cpp
  clients/gtest/auxiliary/larfg_gtest.cpp
  docs/reference/auxiliary.rst
  library/include/rocsolver/rocsolver-functions.h
  library/src/auxiliary/rocauxiliary_lacgv.cpp
  library/src/auxiliary/rocauxiliary_lacgv.hpp
  library/src/auxiliary/rocauxiliary_larf.cpp
  library/src/auxiliary/rocauxiliary_larf.hpp
  library/src/auxiliary/rocauxiliary_larfg.cpp
  library/src/auxiliary/rocauxiliary_larfg.hpp
Labels: noOptimizations

#763 Two fixes for the Jacobi eigensolver
  library/src/lapack/roclapack_syevj_heevj.cpp
  library/src/lapack/roclapack_syevj_heevj.hpp
  library/src/lapack/roclapack_syevj_heevj_batched.cpp
  library/src/lapack/roclapack_syevj_heevj_strided_batched.cpp
Labels: noOptimizations

#759 Added small-size larfg and larf kernels
  CHANGELOG.md
  library/src/CMakeLists.txt
  library/src/auxiliary/rocauxiliary_larf.hpp
  library/src/auxiliary/rocauxiliary_larfg.hpp
  library/src/auxiliary/rocauxiliary_latrd.hpp
  library/src/include/ideal_sizes.hpp
  library/src/include/lapack_device_functions.hpp
  library/src/include/lib_device_helpers.hpp
  library/src/include/rocsolver_run_specialized_kernels.hpp
  library/src/lapack/roclapack_geqr2.hpp
  library/src/lapack/roclapack_sytd2_hetd2.hpp
  library/src/specialized/rocauxiliary_larf_specialized_kernels.hpp
  library/src/specialized/rocauxiliary_larf_specialized_kernels_c.cpp
  library/src/specialized/rocauxiliary_larf_specialized_kernels_d.cpp
  library/src/specialized/rocauxiliary_larf_specialized_kernels_s.cpp
  library/src/specialized/rocauxiliary_larf_specialized_kernels_z.cpp
  library/src/specialized/rocauxiliary_larfg_specialized_kernels.hpp
  library/src/specialized/rocauxiliary_larfg_specialized_kernels_c.cpp
  library/src/specialized/rocauxiliary_larfg_specialized_kernels_d.cpp
  library/src/specialized/rocauxiliary_larfg_specialized_kernels_s.cpp
  library/src/specialized/rocauxiliary_larfg_specialized_kernels_z.cpp
Labels: noOptimizations

#768 Drop use of f16c instructions
  clients/benchmarks/CMakeLists.txt
  clients/gtest/CMakeLists.txt
Labels: noOptimizations, noExtendedCI

#634 Load rocsparse using dlopen
  CHANGELOG.md
  CMakeLists.txt
  docs/installation/installlinux.rst
  install.sh
  library/src/CMakeLists.txt
  library/src/common/rocsparse.cpp
  library/src/include/rocsparse.hpp
  library/src/refact/rocrefact_csrrf_analysis.cpp
  library/src/refact/rocrefact_csrrf_refactchol.cpp
  library/src/refact/rocrefact_csrrf_refactlu.cpp
  library/src/refact/rocrefact_csrrf_solve.cpp
  library/src/refact/rocrefact_csrrf_splitlu.cpp
  library/src/refact/rocrefact_csrrf_splitlu.hpp
  library/src/refact/rocrefact_csrrf_sumlu.cpp
  library/src/refact/rocrefact_csrrf_sumlu.hpp
  library/src/refact/rocsolver_rfinfo.cpp
Labels: noOptimizations, noExtendedCI

#765 Use rocBLAS gemm_64
  library/src/include/rocblas.hpp
  library/src/specialized/roclapack_gemm_specialized_kernels.hpp
Labels: noOptimizations

#773 Update documentation requirements
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: ci:docs-only, documentation

#767 Add 64-bit version of geqrf, geqr2
  CHANGELOG.md
  clients/common/lapack/testing_geqr2_geqrf.cpp
  clients/common/lapack/testing_geqr2_geqrf.hpp
  clients/common/misc/rocsolver.hpp
  clients/common/misc/rocsolver_dispatcher.hpp
  clients/gtest/lapack/geqr2_geqrf_gtest.cpp
  docs/reference/lapack.rst
  library/include/rocsolver/rocsolver-functions.h
  library/src/auxiliary/rocauxiliary_labrd.hpp
  library/src/auxiliary/rocauxiliary_lacgv.cpp
  library/src/auxiliary/rocauxiliary_larf.cpp
  library/src/auxiliary/rocauxiliary_larfg.cpp
  library/src/auxiliary/rocauxiliary_orm2l_unm2l.hpp
  library/src/auxiliary/rocauxiliary_orm2r_unm2r.hpp
  library/src/auxiliary/rocauxiliary_orml2_unml2.hpp
  library/src/include/lib_device_helpers.hpp
  library/src/lapack/roclapack_gebd2.hpp
  library/src/lapack/roclapack_gebrd.hpp
  library/src/lapack/roclapack_gelq2.hpp
  library/src/lapack/roclapack_geql2.hpp
  library/src/lapack/roclapack_geqr2.cpp
  library/src/lapack/roclapack_geqr2.hpp
  library/src/lapack/roclapack_geqr2_batched.cpp
  library/src/lapack/roclapack_geqr2_strided_batched.cpp
  library/src/lapack/roclapack_geqrf.cpp
  library/src/lapack/roclapack_geqrf.hpp
  library/src/lapack/roclapack_geqrf_batched.cpp
  library/src/lapack/roclapack_geqrf_strided_batched.cpp
  library/src/lapack/roclapack_gerq2.hpp
Labels: noOptimizations
