Repository ROCm/rocSOLVER, pull requests merged in 2024-11, with the labels that each got.

#832 Emulation Test Filters
  rtest.py
  rtest.xml
Labels: noOptimizations

#842 Fix static builds (#840)
  library/src/CMakeLists.txt
  library/src/refact/rocsolver_rfinfo.cpp
Labels: ci:static-libraries

#844 remove non production gfx
  CMakeLists.txt
Labels: noExtendedCI

#843 Enable offload-compress when available
  CMakeLists.txt
  library/src/CMakeLists.txt
Labels: noExtendedCI

#826 Potential improvement to set/restore_diag in GEQR2
  library/src/auxiliary/rocauxiliary_larfg.hpp
  library/src/include/rocsolver_run_specialized_kernels.hpp
  library/src/lapack/roclapack_geqr2.hpp
  library/src/specialized/rocauxiliary_larfg_specialized_kernels.hpp
Labels: noOptimizations

#845 Add LASR API
  CHANGELOG.md
  clients/CMakeLists.txt
  clients/benchmarks/client.cpp
  clients/common/auxiliary/testing_lasr.cpp
  clients/common/auxiliary/testing_lasr.hpp
  clients/common/misc/lapack_host_reference.cpp
  clients/common/misc/lapack_host_reference.hpp
  clients/common/misc/rocsolver.hpp
  clients/common/misc/rocsolver_arguments.hpp
  clients/common/misc/rocsolver_dispatcher.hpp
  clients/gtest/CMakeLists.txt
  clients/gtest/auxiliary/lasr_gtest.cpp
  common/include/rocsolver_datatype2string.hpp
  docs/reference/auxiliary.rst
  docs/reference/intro.rst
  docs/reference/types.rst
  library/include/rocsolver/rocsolver-extra-types.h
  library/include/rocsolver/rocsolver-functions.h
  library/src/CMakeLists.txt
  library/src/auxiliary/rocauxiliary_lasr.cpp
  library/src/auxiliary/rocauxiliary_lasr.hpp
  library/src/include/lib_host_helpers.hpp
  library/src/include/rocsolver_logvalue.hpp
Labels: noOptimizations

#850 Fix larfg template mismatch
  library/src/auxiliary/rocauxiliary_larfg.hpp
  library/src/include/rocsolver_run_specialized_kernels.hpp
  library/src/specialized/rocauxiliary_larfg_specialized_kernels.hpp
Labels: noOptimizations, ci:no-ccache

#846 remove non production gfx (#844)
  CMakeLists.txt
Labels: noExtendedCI

#854 Enable hashing output for sygvdx
  clients/benchmarks/client.cpp
  clients/common/containers/host_strided_batch_vector.hpp
  clients/common/lapack/testing_getf2_getrf.hpp
  clients/common/lapack/testing_potf2_potrf.hpp
  clients/common/lapack/testing_syevx_heevx.hpp
  clients/common/lapack/testing_sygvdx_hegvdx.hpp
  clients/common/lapack/testing_sygvx_hegvx.hpp
  clients/common/misc/rocsolver_arguments.hpp
  clients/common/misc/rocsolver_test.hpp
Labels: noOptimizations

#847 Optimize Jacobi eigensolver (WIP)
  CHANGELOG.md
  library/src/include/lib_host_helpers.hpp
  library/src/lapack/roclapack_syevj_heevj.hpp
Labels: ci:no-ccache

#856 Fix debug build (hybrid bdsqr).
  library/src/auxiliary/rocauxiliary_bdsqr_hybrid.hpp
Labels: noOptimizations

#857 bump versions and prepare changelog for new dev cycle
  CHANGELOG.md
  CMakeLists.txt
  bump_rocsolver_version.sh
  library/CMakeLists.txt
Labels: noCI

#849 Fix codeowner syntax for docs
  .github/CODEOWNERS
Labels: ci:docs-only, documentation
