Repository ROCm/rocSOLVER, pull requests merged in 2024-02, with the labels that each got.

#654 Added stedcj
  clients/CMakeLists.txt
  clients/common/testing_stedcj.cpp
  clients/gtest/stedc_gtest.cpp
  clients/include/rocsolver.hpp
  clients/include/rocsolver_dispatcher.hpp
  clients/include/testing_stedcj.hpp
  docs/api/lapacklike.rst
  library/src/CMakeLists.txt
  library/src/auxiliary/rocauxiliary_stedc.hpp
  library/src/auxiliary/rocauxiliary_stedcj.cpp
  library/src/auxiliary/rocauxiliary_stedcj.hpp
  library/src/lapack/roclapack_syevdj_heevdj.hpp
Labels: noOptimizations

#657 Reduce rocblas minimum version to 4.1
  CMakeLists.txt
  bump_rocsolver_version.sh
Labels: noOptimizations, noExtendedCI

#668 Add rocsolver team as code owners for docs
  .github/CODEOWNERS
Labels: noExtendedCI, ci:docs-only

#661 Fix for failing large-size getrf tests
  clients/common/lapack_host_reference.cpp
  clients/gtest/getrf_large_gtest.cpp
  clients/include/lapack_host_reference.hpp
  clients/include/norm.hpp
  clients/include/testing_getrf_large.hpp
Labels: noOptimizations

#671 Fix documentation warnings and errors
  docs/Dockerfile
  docs/doxygen/Doxyfile
  docs/run_doxygen.sh
Labels: ci:docs-only, documentation

#666 Add ifndef guards to macros
  library/src/include/ideal_sizes.hpp
  library/src/include/lib_macros.hpp
Labels: noOptimizations, noExtendedCI

#667 cmake: add fmt/rocsparse as package deps if building static lib
  library/src/CMakeLists.txt
Labels: noOptimizations, noExtendedCI

#670 Rename install script arguments
  CHANGELOG.md
  install.sh
Labels: noOptimizations

#681 cmake: add rocblas back as regular package dependency, not just static
  library/src/CMakeLists.txt
Labels: noOptimizations
