Repository ROCm/rocSOLVER, pull requests merged in 2025-01, with the labels that each got.

#872 Update license file for 2025
  LICENSE.md
Labels: ci:docs-only, documentation

#876 Cherry-pick to release-staging/rocm-rel-6.4: Update license file for 2025 (#872)
  LICENSE.md
Labels: ci:docs-only, documentation

#879 Fix tolerance for HEGVDX tests
  clients/common/lapack/testing_sygvdx_hegvdx.hpp
Labels: noOptimizations, ci:extended

#869 Reduced memory usage for SYEVD
  CHANGELOG.md
  library/src/auxiliary/rocauxiliary_stedc.hpp
  library/src/lapack/roclapack_syevd_heevd.hpp
  library/src/lapack/roclapack_sytrd_hetrd.hpp
Labels: noOptimizations, ci:no-ccache

#883 use rocjenkins xml instead of hardcoded
  .jenkins/staticanalysis.groovy
Labels: noOptimizations, ci:no-ccache

#882 Update SYGVDX/HEGVDX tests' tolerance
  clients/common/lapack/testing_sygvdx_hegvdx.hpp
Labels: ci:no-ccache

#877 Cherry pick tests' fixes (#810) into 6.4
  clients/common/lapack/testing_sygvdx_hegvdx.hpp
  clients/common/matrix_utils/host_matrix.hpp
  clients/common/matrix_utils/matrix_utils_detail.hpp
  clients/common/misc/clss.hpp
Labels: noOptimizations, ci:no-ccache, ci:extended

#887 Fix three broken links to rocBLAS and netlib
  docs/index.rst
  docs/reference/deprecated.rst
Labels: ci:docs-only, documentation
