Repository ROCm/rocSOLVER, pull requests merged in 2025-05, with the labels that each got.

#827 link is fixed and also changed 'modes of logging' to 'logging modes' …
  docs/howto/logging.rst
Labels: ci:docs-only, documentation

#911 Fix tests in debug build
  .jenkins/debug.groovy
  library/src/auxiliary/rocauxiliary_bdsqr.hpp
  library/src/include/lib_device_helpers.hpp
Labels: noOptimizations, ci:debug

#938 Hybrid support for STEQR
  CHANGELOG.md
  clients/common/auxiliary/testing_steqr.hpp
  clients/common/lapack/testing_syev_heev.hpp
  clients/gtest/auxiliary/steqr_gtest.cpp
  library/include/rocsolver/rocsolver-extra-types.h
  library/include/rocsolver/rocsolver-functions.h
  library/src/auxiliary/rocauxiliary_bdsqr_hybrid.hpp
  library/src/auxiliary/rocauxiliary_steqr.hpp
  library/src/common/rocsolver_handle.cpp
  library/src/include/lapack_device_functions.hpp
  library/src/include/lib_device_helpers.hpp
  library/src/include/rocsolver_handle.hpp
  library/src/include/rocsolver_hybrid_storage.hpp
Labels: noOptimizations

#944 Optimize larft
  CHANGELOG.md
  clients/gtest/auxiliary/larft_gtest.cpp
  library/src/auxiliary/rocauxiliary_larft.hpp
  library/src/include/ideal_sizes.hpp
Labels: noOptimizations

#937 Use gfx10 and gfx12 generic targets
  CMakeLists.txt
Labels: gfxall
