Repository ROCm/rocSOLVER, pull requests merged in 2025-04, with the labels that each got.

#923 Revert "Use new lasr in bdsqr"
  CHANGELOG.md
  library/src/auxiliary/rocauxiliary_bdsqr.hpp
Labels: noOptimizations

#919 First phase of rocSOLVER docs refresh
  docs/conf.py
  docs/howto/clients.rst
  docs/howto/logging.rst
  docs/howto/memory.rst
  docs/howto/using.rst
  docs/index.rst
  docs/installation/index.rst
  docs/installation/installlinux.rst
  docs/reference/auxiliary.rst
  docs/reference/helpers.rst
  docs/reference/intro.rst
  docs/reference/lapack.rst
  docs/reference/lapacklike.rst
  docs/reference/precision.rst
  docs/reference/refact.rst
  docs/reference/tuning.rst
  docs/reference/types.rst
  docs/sphinx/_toc.yml.in
Labels: ci:docs-only, documentation

#934 gfx target on PRs to develop
  .jenkins/common.groovy
Labels: gfxall
