Repository ROCm/rocSOLVER, pull requests merged in 2025-03, with the labels that each got.

#902 Add gfx950 to default build targets
  CMakeLists.txt
Labels: noExtendedCI

#897 Use new LASR in STEQR and BDSQR and parallelize STEQR
  library/src/auxiliary/rocauxiliary_bdsqr.hpp
  library/src/auxiliary/rocauxiliary_bdsqr_hybrid.hpp
  library/src/auxiliary/rocauxiliary_lasr.hpp
  library/src/auxiliary/rocauxiliary_stedc.hpp
  library/src/auxiliary/rocauxiliary_steqr.hpp
  library/src/include/lib_device_helpers.hpp
Labels: noOptimizations, runPerformance

#901 Use stedc instead of sterf in syevd
  clients/common/auxiliary/testing_bdsqr.hpp
  clients/common/auxiliary/testing_sterf.hpp
  clients/common/lapack/testing_gesvd.hpp
  clients/common/lapack/testing_syev_heev.hpp
  clients/common/lapack/testing_syevd_heevd.hpp
  clients/gtest/lapack/syevd_heevd_gtest.cpp
  library/src/lapack/roclapack_syevd_heevd.cpp
  library/src/lapack/roclapack_syevd_heevd.hpp
  library/src/lapack/roclapack_syevd_heevd_batched.cpp
  library/src/lapack/roclapack_syevd_heevd_strided_batched.cpp
  library/src/lapack/roclapack_sygvd_hegvd.cpp
  library/src/lapack/roclapack_sygvd_hegvd.hpp
  library/src/lapack/roclapack_sygvd_hegvd_batched.cpp
  library/src/lapack/roclapack_sygvd_hegvd_strided_batched.cpp
Labels: noOptimizations

#903 Prefer ROCmCMakeBuildTools to ROCM
  cmake/get-rocm-cmake.cmake
Labels: noOptimizations, noExtendedCI

#899 Implement `gesdd`
  CHANGELOG.md
  clients/CMakeLists.txt
  clients/common/lapack/testing_gesdd.cpp
  clients/common/lapack/testing_gesdd.hpp
  clients/common/misc/rocsolver.hpp
  clients/common/misc/rocsolver_dispatcher.hpp
  clients/gtest/CMakeLists.txt
  clients/gtest/lapack/gesdd_gtest.cpp
  library/include/rocsolver/rocsolver-functions.h
  library/src/CMakeLists.txt
  library/src/lapack/roclapack_gesdd.cpp
  library/src/lapack/roclapack_gesdd.hpp
  library/src/lapack/roclapack_gesdd_batched.cpp
  library/src/lapack/roclapack_gesdd_strided_batched.cpp
Labels: noOptimizations

#906 Fix calls to `syevd_getMemorySize`
  library/src/lapack/roclapack_gesdd.cpp
  library/src/lapack/roclapack_gesdd.hpp
  library/src/lapack/roclapack_gesdd_batched.cpp
  library/src/lapack/roclapack_gesdd_strided_batched.cpp
Labels: noOptimizations

#900 Remove support for gfx940, gfx941
  library/src/specialized/roclapack_trsm_specialized_kernels.hpp
Labels: noOptimizations, ci:no-ccache

#913 Fix CMake version number
  CMakeLists.txt
Labels: ci:docs-only, documentation

#918 Bump versions and prepare changelog for new dev cycle
  CHANGELOG.md
  CMakeLists.txt
  bump_rocsolver_version.sh
  library/CMakeLists.txt
Labels: noOptimizations

#920 Docs: Add Precision Support Page
  docs/index.rst
  docs/reference/index.rst
  docs/reference/precision.rst
  docs/sphinx/_toc.yml.in
Labels: ci:docs-only, documentation
